services:
  rust-sqlx-pg:
    image: postgres:latest
    container_name: grpc-server
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rust_sqlx_pg
